# Use the official NGINX image from Docker Hub
FROM nginx:alpine

# Expose port 80 for HTTP traffic
EXPOSE 80

# Run NGINX in the foreground (this is the default command in the NGINX image)
CMD ["nginx", "-g", "daemon off;"]
